name: Build & Test CI


on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkouts@v2

      - name: Install Dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Test
        run: yarn test
